---
title: "Survey Codes for Variables"
author: "Cory J. Cascalheira"
date: "March 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Understanding the Variables
___
The *Initial Attraction Online* survey was downloaded as a CSV.

*SurveyMonkey* returned a wide, untidy file with dummy variables and many missing values. During pre-processing, the data were split into two data frames, variables were assigned names, and image selection were linked to their filename.

## Radio Button Variables
___
Some questions required participants to choose only one response and were coded as follows:

**General Variables**

1. **id**: participant identification
2. **start**: starting datetime of the survey
3. **end**: ending datetime of the survey
4. **consent**: did participant agree to participate?

**Demographics**

5. **sex_orient**: sexual orientation
6. **gender**: gender identity
7. **single**: relationship status
8. **out**: disclosure of sexual orientation
9. **pic**: content of public-facing profile picture
10. **age**: age
11. **body**: physical appearance of body
12. **ethnicity**: ethnicity
13. **sex_position**: sexual position 

**Social Identity Scale**

14. **si_popular**: "My popularity with other guys, their willingness to chat with or meet me"
15. **si_racialgrp**: "My sense of belonging to my own racial group"
16. **si_react**: "The ways in which other people react to what I say and do"
17. **si_appearance**: "My physical appearance: my height, my weight, and the shape of my body"
18. **si_masc**: "My masculinity, how manly others think I am"
19. **si_reputation**: "My reputation, what others think of me"
20. **si_attractive**: "My attractiveness to other guys"
21. **si_skincolor**: "The color of my skin"
22. **si_gestures**: "My gestures and mannerisms, whether others can tell if I am gay"
23. **si_socialbhvr**: "My social behavior, such as the way I act when meeting other men"

**Forced Choice Image Selection**

24. **fc_1**: white-em-01, black-em-03, white-em-03, asian-hm-02
25. **fc_2**: black-hm-05, black-em-02, white-hm-02, black-hm-04
26. **fc_3**: latino-hm-01, black-em-01, white-em-05, white-hm-03
27. **fc_4**: asian-em-04, white-hm-04, black-em-05, asian-em-03
28. **fc_5**: black-hm-03, latino-em-03, black-hm-02, asian-hm-04
29. **fc_6**: black-em-04, latino-em-02, asian-hm-03, white-em-04
30. **fc_7**: latino-hm-04, latino-hm-03, asian-em-05, asian-hm-01
31. **fc_8**: white-hm-01, latino-hm-05, latino-em-05, white-hm-05
32. **fc_9**: black-hm-01, asian-em-01, latino-hm-02, white-em-02
33. **fc_10**: asian-hm-05, latino-em-01, latino-em-04, asian-em-02

## Dummy Choice Variables
___
Some questions allowed participants to select more than one answer. *SurveyMonkey* coded each answer choice as a separate variable. If a participant selected the choice, then the response was recorded for that observation. Otherwise, the value was missing. 

All missing categorical values, `NA`, were replaced with the character string `"none"`.

**General**

1. **id**: participant identification

**Past App Use**

2. **pa_a4a**: Adam4Adam
3. **pa_dh**: Daddyhunt
4. **pa_dsc**: DISCO
5. **pa_grdr**: Grindr
6. **pa_grzz**: Grizzly
7. **pa_grwl**: Growlr
8. **pa_hrnt**: Hornet
9. **pa_jckd**: Jack'd
10. **pa_okc**: OkCupid
11. **pa_scf**: Scruff
12. **pa_srg**: Surge
13. **pa_tdr**: Tinder
14. **pa_other**: Some other app

**Current App Use**

15. **ca_a4a**: Adam4Adam
16. **ca_dh**: Daddyhunt
17. **ca_dsc**: DISCO
18. **ca_grdr**: Grindr
19. **ca_grzz**: Grizzly
20. **ca_grwl**: Growlr
21. **ca_hrnt**: Hornet
22. **ca_jckd**: Jack'd
23. **ca_okc**: OkCupid
24. **ca_scf**: Scruff
25. **ca_srg**: Surge
26. **ca_tdr**: Tinder
27. **ca_other**: Some other app
28. **ca_none**: Not using an app

**Hidden Information**

29. **hi_profpic**: profile picture
30. **hi_age**: age
31. **hi_body**: body type
32. **hi_ethnty**: ethnicity
33. **hi_sexpost**: sexual position
34. **hi_none**: none, don't hide anything

**Free Choice Image Selection Cluster 1**

35. **black-hm-03**: Black heteronormative picture 03
36. **latino-em-03**: Latino effeminate picture 03
37. **black-hm-02**: Black heteronormative picture 02
38. **asian-hm-04**: Asian heteronormative picture 04
39. **asian-em-04**: Asian effeminate picture 04
40. **white-hm-04**: White heteronormative picture 04
41. **black-em-05**: Black effeminate picture 05
42. **asian-em-03**: Asian effeminate picture 03
43. **latino-hm-01**: Latino heteronormative picture 01
44. **black-em-01**: Black effeminate picture 01

**Free Choice Image Selection Cluster 2**

45. **white-em-05**: White effeminate picture 05
46. **white-hm-03**: White heteronormative picture 03
47. **black-hm-05**: Black heteronormative picture 05
48. **black-em-02**: Black effeminate picture 02
49. **white-hm-02**: White heteronormative picture 02
50. **black-hm-04**: Black heteronormative picture 04
51. **white-em-01**: White effeminate picture 01
52. **black-em-03**: Black effeminate picture 03
53. **white-em-03**: White effeminate picture 03
54. **asian-hm-02**: Asian heteronormative picture 02

**Free Choice Image Selection Cluster 3**

55. **asian-hm-05**: Asian heteronormative picture 05
56. **latino-em-01**: Latino effeminate picture 01
57. **latino-em-04**: Latino effeminate picture 04
58. **asian-em-02**: Asian effeminate picture 02
59. **black-hm-01**: Black heteronormative picture 01
60. **asian-em-01**: Asian effeminate picture 01
61. **latino-hm-02**: Latino heteronormative picture 02
62. **white-em-02**: White effeminate picture 02
63. **white-hm-01**: White heteronormative picture 01
64. **latino-hm-05**: Latino heteronormative picture 05

**Free Choice Image Selection Cluster 4**

65. **latino-em-05**: Latino effeminate picture 05
66. **white-hm-05**: White heteronormative picture 05
67. **latino-hm-04**: Latino heteronormative picture 04
68. **latino-hm-03**: Latino heteronormative picture 03
69. **asian-em-05**: Asian effeminate picture 05
70. **asian-hm-01**: Asian heteronormative picture 01
71. **black-em-04**: Black effeminate picture 04
72. **latino-em-02**: Latino effeminate picture 02
73. **asian-hm-03**: Asian heteronormative picture 03
74. **white-em-04**: White effeminate picture 04

# Recoding Social Identity Scale
___
A technical problem prevented the social identity variables from being recoded with `fct_recode`, `dplyr::recode`, and `car::recode`. Thus, a rather sloppy workaround was used.

First, I took note of the default ordering of factor levels. When coerced to numeric, the ordering did not abide by the appropriate Likert-type scale. For example, the high-anchor *extremely important to my sense of who I am* should have be coded as a `5`, but alphabetical ordering coded this option as a `1`. Manual recoding was necessary.

1. "Extremely important to my sense of who I am" = **5**
2. "Not important to my sense of who I am" = **1**
3. "Slightly important to my sense of who I am" = **2**
4. "Somewhat important to my sense of who I am" = **3**
5. "Very important to my sense of who I am" = **4**